name: CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build & Push Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # log into your container registry (set these secrets in Settings > Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build & push backend
      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: yourdockerhubuser/mediafinder-backend:latest

      # build & push frontend
      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: yourdockerhubuser/mediafinder-frontend:latest
